import { DbStorage } from '../server/db';
import { InsertProduct } from '@shared/schema';

const sampleProducts: InsertProduct[] = [
      {
        name: "Samsung Galaxy S23 Ultra",
        description: "Premium flagship smartphone with 200MP camera, S Pen, and powerful performance for ultimate productivity.",
        price: "124999",
        originalPrice: "149999",
        category: "Electronics",
        brand: "Samsung",
        image: "https://broken-image-url.com/missing-image.jpg",
        rating: "4.5",
        reviewCount: 1248,
        inStock: true,
        badge: "Bestseller",
      },
      {
        name: "Apple iPhone 15 Pro",
        description: "Revolutionary A17 Pro chip, titanium design, and advanced camera system for pro-level photography.",
        price: "134900",
        originalPrice: "154900",
        category: "Electronics",
        brand: "Apple",
        image: "https://placehold.co/400x400/2874f0/ffffff?text=iPhone+15",
        rating: "4.8",
        reviewCount: 2156,
        inStock: true,
        badge: "Bestseller",
      },
      {
        name: "Sony WH-1000XM5 Headphones",
        description: "Industry-leading noise cancellation, premium sound quality, and all-day comfort.",
        price: "29990",
        originalPrice: "34990",
        category: "Electronics",
        brand: "Sony",
        image: "https://placehold.co/400x400/2874f0/ffffff?text=Sony+XM5",
        rating: "4.7",
        reviewCount: 856,
        inStock: true,
        badge: null,
      },
      {
        name: "Nike Air Max 270",
        description: "Iconic Air cushioning meets modern style. Maximum comfort for all-day wear.",
        price: "12995",
        originalPrice: "16995",
        category: "Fashion",
        brand: "Nike",
        image: "https://placehold.co/400x400/f0a82e/ffffff?text=Air+Max",
        rating: "4.4",
        reviewCount: 542,
        inStock: true,
        badge: "New Arrival",
      },
      {
        name: "Adidas Ultraboost 22",
        description: "Energy-returning cushioning and adaptive fit for the ultimate running experience.",
        price: "16999",
        originalPrice: "21999",
        category: "Fashion",
        brand: "Adidas",
        image: "https://placehold.co/400x400/f0a82e/ffffff?text=Ultraboost",
        rating: "4.6",
        reviewCount: 723,
        inStock: true,
        badge: null,
      },
      {
        name: "LG 55\" OLED TV",
        description: "Perfect blacks, infinite contrast, and stunning colors. Cinema-quality viewing at home.",
        price: "139990",
        originalPrice: "179990",
        category: "Electronics",
        brand: "LG",
        image: "https://invalid-cdn.nowhere.com/missing-tv.png",
        rating: "4.9",
        reviewCount: 324,
        inStock: true,
        badge: "Bestseller",
      },
      {
        name: "Premium Cotton Bedsheet Set",
        description: "Luxurious 400-thread count cotton bedsheets. King size with 2 pillow covers.",
        price: "2499",
        originalPrice: "4999",
        category: "Home & Kitchen",
        brand: "HomeStory",
        image: "https://placehold.co/400x400/10b981/ffffff?text=Bedsheet",
        rating: "4.3",
        reviewCount: 1892,
        inStock: true,
        badge: null,
      },
      {
        name: "Air Fryer 5L Digital",
        description: "Healthy cooking made easy. 8 preset modes, digital display, dishwasher safe.",
        price: "4999",
        originalPrice: "7999",
        category: "Home & Kitchen",
        brand: "Philips",
        image: "https://placehold.co/400x400/10b981/ffffff?text=Air+Fryer",
        rating: "4.5",
        reviewCount: 2341,
        inStock: true,
        badge: "Bestseller",
      },
      {
        name: "The Psychology of Money",
        description: "Timeless lessons on wealth, greed, and happiness by Morgan Housel.",
        price: "399",
        originalPrice: "599",
        category: "Books",
        brand: "Jaico",
        image: "https://placehold.co/400x400/8b5cf6/ffffff?text=Psychology",
        rating: "4.8",
        reviewCount: 5623,
        inStock: true,
        badge: "Bestseller",
      },
      {
        name: "Atomic Habits",
        description: "An easy and proven way to build good habits and break bad ones by James Clear.",
        price: "449",
        originalPrice: "699",
        category: "Books",
        brand: "Penguin",
        image: "https://placehold.co/400x400/8b5cf6/ffffff?text=Atomic",
        rating: "4.9",
        reviewCount: 8934,
        inStock: true,
        badge: "Bestseller",
      },
      {
        name: "Yoga Mat Premium",
        description: "Non-slip, eco-friendly yoga mat with alignment marks. 6mm thickness for comfort.",
        price: "1299",
        originalPrice: "1999",
        category: "Sports",
        brand: "Reebok",
        image: "https://placehold.co/400x400/ef4444/ffffff?text=Yoga+Mat",
        rating: "4.4",
        reviewCount: 892,
        inStock: true,
        badge: "New Arrival",
      },
      {
        name: "Dumbbell Set 20kg",
        description: "Adjustable dumbbells with chrome finish. Perfect for home workouts.",
        price: "2999",
        originalPrice: "4999",
        category: "Sports",
        brand: "Kore",
        image: "https://placehold.co/400x400/ef4444/ffffff?text=Dumbbells",
        rating: "4.6",
        reviewCount: 445,
        inStock: true,
        badge: null,
      },
    ];

async function seed() {
  const storage = new DbStorage();
  console.log("Seeding products...");
  for (const product of sampleProducts) {
    await storage.createProduct(product);
  }
  console.log("Seeding complete!");
}

seed().catch((err) => {
  console.error("Error seeding database:", err);
  process.exit(1);
});
